# Change these first
owner: parcoApp # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Kraken
    url: https://kraken.parcoapp.com
  - name: Ghostbuster
    url: https://parcoapp-apis-ghostbuster.echo.parcoapp.com
  - name: Tesseract
    url: https://parcoapp-apis-tesseract.echo.parcoapp.com
  - name: Andares
    url: $SECRET_SITE_ANDARES
  - name: Dostop
    url: $SECRET_SITE_DOSTOP

assignees:
  - norman404

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: /upptime
  theme: dark
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** pagina de estatus de ParcoApp"
  introMessage: Cualquier cosa, contactar con soporte.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
